import type { Metadata } from "next";
import "../styles/globals.css";
import { Inter, Roboto_Mono } from "next/font/google";
import TopNav from "@/components/topnav";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const robotoMono = Roboto_Mono({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`font-sans ${inter.variable} ${robotoMono.variable} antialiased`}
			>
				<TopNav />
				{children}
			</body>
		</html>
	);
}
